#product服务端口
server:
  port: 8771

#product服务名称
spring:
  application:
    name: product-service

#指定Eureka注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

env: dev

